### PR TITLE
Prefix Removing encoders 

### PR DESCRIPTION
**Pull request by vitorpamplona**
3 special encoders that simply remove the schema part of the following URI styles: 

1. DID:
2. DID:WEB:
3. URN:UVCI:

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Later on, these should also not percent-encode `:` to `%3A`

**Comment by dpjanes** [comment]
I think this is making too many coders. Let's just have one called "did", and it can take a "prefix" argument (in templates) for what a leading "~" means, which would be by default "did:".

Look at the "url: encoder - there's a pretty good example there (though it doesn't use a prefix).

**Comment by dpjanes** [comment]
The "url" encoder encodes "/" as "~". Basically did needs to be follow the same logic, except code ":" as "~".

**Comment by vitorpamplona** [comment]
Well, I coded them as a single prefix-encoder and then 3 classes just to specialize into each prefix. 

Hum... I don't see a URL encoder. Where is it?

**Comment by dpjanes** [comment]
Hmmm, something has gone astray when my system crashed. I will look on an old computer.

**Comment by vitorpamplona** [comment]
oh man.. sorry for adding more things to the same PR. I forgot that this is automated...

**Comment by dpjanes** [comment]
I'm merging and will sort out things on the weekend

**Comment by dpjanes** [comment]
My URL encoder has disappeared without a trace. Including test cases. It's so gone I almost feel like I was imagining it.

**Comment by dpjanes** [comment]
There's a URL encoder there now, I found it on a Windows machine I was temporarily using.

**Comment by dpjanes** [comment]
I think if the URL encoder takes (in the templates) argument a "prefix" argument, we can make it cover all the DID cases.

**Comment by vitorpamplona** [comment]
I am not sure why the URL needs escaping there. Otherwise, I agree. 

Another option is to just have a single prefix_remover coder and pass the prefix as a parameter in the templates.json, like i did with the array template:

Something like: 

```
  "data:1": {
    "columns": [
       {"path": "people", "encoder": "prefix_remover", "encoder_param": "https"},
    ],
    "template": { ... }
  },
```

**Comment by vitorpamplona** [comment]
Or like this: 

```

  "data:1": {
    "columns": [
       {"path": "people", "encoder": "prefix_remover", "encoder_param": {prefix:"https"}},
    ],
    "template": { ... }
  },```

**Comment by dpjanes** [comment]
URL encode preferentially encodes "/" as "~", and assumes prefix "https://" (but this can be changed)
URN encoder will preferentially encode ":" as "~", and will assume (I guess) prefix "urn:"

I'm not trying to make everything _too_ parameterized, otherwise we become a security threat, and more difficult to understand.

**Comment by dpjanes** [comment]
Building on your idea, in theory we could make string take a "prefix" and "character to encode as ~" and get rid of url and urn

**Comment by vitorpamplona** [comment]
I keep thinking about encoders that are unique to a use case. The UVCI, for instance, is just an EU thing. There has to be a way for the implementer to create an encoder and declare it on the templates.json

**Comment by dpjanes** [comment]
Why invent problems? Why not let them come to us naturally.

Also note that if you are talking about limited number of URIs that can be enumerated, which might happen in many use cases, `string` very efficiently deals with - 2 or 3 bytes.

**Comment by vitorpamplona** [comment]
Agree. 

I like the prefix_remover generalization idea (below) better than making 3-4 encoders that only change the prefix string: 

```
  "data:1": {
    "columns": [
       {"path": "people", "encoder": "prefix_remover", "encoder_param": {prefix:"https"}},
    ],
    "template": { ... }
  },``
```

**Comment by dpjanes** [comment]
The string encoder has `prefix` (an array of prefixes) and `escape` (the character to escape to `~`, normally ` `) coded. I have not written test cases yet.

**Pull request merged**
